name: backend image publish

on:
  push:
    branches: [ "main" ]

jobs:
  upload_img:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'fullstack-backend'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Log in to Docker Hub
        run: docker login -u=quinnfontys -p="${{ secrets.DOCKER_PASSWORD }}"    
      - name: Build the Docker image
        run: mvn clean package
        run: docker build -t quinnfontys/backend .
      - name: Push to Docker
        run: docker push quinnfontys/frontend:latest