name: Create and Publish frontend webshop image

on:
  push:
    branches: [ "main" ]

jobs:
  upload_img:

























    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'fullstack-front'
    steps:
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build -t quinnfontys/frontend .
      -name: Push to Docker
        run: docker push ${{secrets.DOCKER_USER}}/frontend:lates
























