name: Frontend admin image publish

on:
  push:
    branches: [ "main" ]

jobs:
  upload_img:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend-admin'
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: docker login -u=quinnfontys -p="${{ secrets.DOCKER_PASSWORD }}"
      - name: Build the Docker image
        run: docker build -t quinnfontys/frontendadmin .
      - name: Push to Docker
        run: docker push quinnfontys/frontendadmin:latest